version: "3.5"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - default
  node-red:
    image: nodered/node-red-docker
    hostname: node-red
    container_name: node-red
    expose:
      - "1880"
    ports:
      - " 1880:1880"