version: "2"
services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /var/mosquitto/config:/mosquitto/config
      - /data/mosquitto/data:/mosquitto/data
      - /var/log/mosquitto:/mosquitto/log
    networks:
      - default
  nodered:
    image: nodered/node-red-docker
    hostname: nodered
    container_name: nodered
    expose:
      - "1880"
    ports:
      - "1880:1880"